# Generated by Django 4.2.7 on 2023-11-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrocerryShop_App', '0002_alter_product_cat_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(),
        ),
    ]
