# Generated by Django 4.2.7 on 2023-11-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrocerryShop_App', '0003_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Liquid'), (2, 'Solid'), (3, 'Vegitables')], verbose_name='Category'),
        ),
    ]
